import { mkdir, writeFile } from "node:fs/promises"
import { dirname } from "node:path"

export type GenerateContractsTypesOptions = {
  /**
   * Module specifier used in the generated file to import the contracts definition.
   * Example: "./lib/contracts" or "@acme/app/contracts".
   */
  contractsImportPath: string
  /**
   * Output file path (absolute or relative to process.cwd()).
   */
  outPath: string
  /**
   * Export name to import from `contractsImportPath`.
   *
   * By default this is `"contracts"`, but you can point it at a larger container
   * (e.g. `"app"`) together with `contractsAccessor`.
   */
  contractsExportName?: string
  /**
   * Optional property accessor appended to the imported export when deriving `Contracts`.
   *
   * Example: if you export `app`, set `contractsExportName: "app"` and
   * `contractsAccessor: ".contracts"` to get `type Contracts = typeof app.contracts`.
   */
  contractsAccessor?: string
  /**
   * Import specifier used for Honostar server types (default: "@honostar/core/server").
   */
  serverImportPath?: string
}

export async function generateContractsTypes(opts: GenerateContractsTypesOptions): Promise<void> {
  const contractsExportName = opts.contractsExportName ?? "contracts"
  const contractsAccessor = opts.contractsAccessor ?? ""
  const serverImportPath = opts.serverImportPath ?? "@honostar/core/server"

  if (contractsAccessor && !contractsAccessor.startsWith(".")) {
    throw new Error(
      `Invalid contractsAccessor "${contractsAccessor}". It must be empty or start with "."`
    )
  }

  const contents = `// This file is auto-generated by the contracts type generator.
// Do not edit manually.
import type { ${contractsExportName} } from ${JSON.stringify(opts.contractsImportPath)}
import type {
  ContractEventName,
  ContractPayload,
  ContractTopicName,
} from ${JSON.stringify(serverImportPath)}

export type Contracts = typeof ${contractsExportName}${contractsAccessor}
export type TopicName = ContractTopicName<Contracts>
export type EventName<Topic extends TopicName> = ContractEventName<Contracts, Topic>
export type Payload<Topic extends TopicName, Event extends EventName<Topic>> = ContractPayload<
  Contracts,
  Topic,
  Event
>
`

  await mkdir(dirname(opts.outPath), { recursive: true })
  await writeFile(opts.outPath, contents, "utf-8")
}
