import { mkdir, writeFile } from "node:fs/promises"
import { dirname } from "node:path"

export type GenerateContractsTypesOptions = {
  /**
   * Module specifier used in the generated file to import the contracts definition.
   * Example: "./lib/contracts" or "@acme/app/contracts".
   */
  contractsImportPath: string
  /**
   * Output file path (absolute or relative to process.cwd()).
   */
  outPath: string
  /**
   * Export name from the contracts module (default: "contracts").
   */
  contractsExportName?: string
  /**
   * Import specifier used for Honostar server types (default: "@honostar/core/server").
   */
  serverImportPath?: string
}

export async function generateContractsTypes(opts: GenerateContractsTypesOptions): Promise<void> {
  const contractsExportName = opts.contractsExportName ?? "contracts"
  const serverImportPath = opts.serverImportPath ?? "@honostar/core/server"

  const contents = `// This file is auto-generated by the contracts type generator.
// Do not edit manually.
import type { ${contractsExportName} } from ${JSON.stringify(opts.contractsImportPath)}
import type {
  ContractEventName,
  ContractPayload,
  ContractTopicName,
} from ${JSON.stringify(serverImportPath)}

export type Contracts = typeof ${contractsExportName}
export type TopicName = ContractTopicName<Contracts>
export type EventName<Topic extends TopicName> = ContractEventName<Contracts, Topic>
export type Payload<Topic extends TopicName, Event extends EventName<Topic>> = ContractPayload<
  Contracts,
  Topic,
  Event
>
`

  await mkdir(dirname(opts.outPath), { recursive: true })
  await writeFile(opts.outPath, contents, "utf-8")
}
