import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, posix, relative } from 'node:path'

export type ManifestEntry = {
  routePath: string
  importPath: string
}

type RoutesConfig = Record<string, string[][]>

type RouteValue = string | RouteNode
interface RouteNode {
  [key: string]: RouteValue
}

export interface GeneratorOptions {
  pagesDir: string
  manifestPath: string
  routesPath: string
  routesConfig?: RoutesConfig
}

function filePathToRoutePath(filePath: string): string {
  let p = filePath
    .replace(/\\/g, '/')
    .replace(/^.*\/pages\//, '')
    .replace(/\.(tsx|ts|mdx|md)$/, '')

  p = p.replace(/\((.+?)\)/g, '')
  p = p.replace(/\[\.{3}.*\]/g, '*')
  p = p.replace(/\[(.+?)\]/g, ':$1')
  p = p.replace(/\/index$/, '')
  if (p === 'index') p = ''
  p = `/${p}`
  return p.replace(/\/\/+/g, '/')
}

function shouldSkip(filePath: string): boolean {
  // Skip files starting with underscore at any level
  return /(^|\/)_[^/]+\.(ts|tsx)$/.test(filePath)
}

function countDynamicSegments(path: string): number {
  return path
    .split('/')
    .filter(seg => seg.startsWith(':') || seg === '*' || seg === '*?' || seg === '**').length
}

async function scanDirectory(dir: string, pattern: RegExp): Promise<string[]> {
  const results: string[] = []

  async function walk(currentPath: string, relativePath = '') {
    const entries = await readdir(currentPath, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = join(currentPath, entry.name)
      const relPath = relativePath ? `${relativePath}/${entry.name}` : entry.name

      if (entry.isDirectory()) {
        await walk(fullPath, relPath)
      } else if (entry.isFile() && pattern.test(entry.name)) {
        results.push(relPath)
      }
    }
  }

  await walk(dir)
  return results
}

async function buildEntries(pagesDir: string, manifestPath: string): Promise<ManifestEntry[]> {
  const entries: ManifestEntry[] = []
  const pattern = /\.(ts|tsx)$/

  const files = await scanDirectory(pagesDir, pattern)

  for (const rel of files) {
    if (shouldSkip(rel)) continue

    const abs = join(pagesDir, rel)
    const routePath = filePathToRoutePath(abs)
    const relativeToManifest = relative(dirname(manifestPath), abs)
    const withoutExt = relativeToManifest.replace(/\.(tsx|ts)$/, '')
    const importPath = `./${posix.join(...withoutExt.split(/[/\\]+/))}`

    entries.push({ routePath, importPath })
  }

  return entries.toSorted((a, b) => {
    const aDynamic = countDynamicSegments(a.routePath)
    const bDynamic = countDynamicSegments(b.routePath)
    if (aDynamic !== bDynamic) return aDynamic - bDynamic
    // When dynamics equal, prefer longer/static paths first so `/issues/new` beats `/issues/:id`
    if (a.routePath.length !== b.routePath.length) return b.routePath.length - a.routePath.length
    return a.routePath.localeCompare(b.routePath)
  })
}

function generateManifestFile(entries: ManifestEntry[]): string {
  const lines: string[] = []
  lines.push('// This file is auto-generated by the route manifest generator.')
  lines.push('// Do not edit manually.')
  lines.push("import type { RouteManifestEntry } from '@/honostar/server'")
  lines.push('')
  lines.push('export const routesManifest: RouteManifestEntry[] = [')
  for (const entry of entries) {
    lines.push('  {')
    lines.push(`    routePath: '${entry.routePath}',`)
    lines.push(`    load: () => import('${entry.importPath}'),`)
    lines.push('  },')
  }
  lines.push(']')
  lines.push('')
  return lines.join('\n')
}

function sanitizeKey(segment: string): string {
  let key = segment.replace(/^:/, '')
  key = key.replace(/\[(\.\.\.)?/, '').replace(/]/g, '')
  if (segment.startsWith('*')) key = 'wildcard'
  if (segment.startsWith('...')) key = `rest${key}`
  if (!key || key === '') key = 'index'
  key = key.replace(/[^A-Za-z0-9]+(\w)/g, (_, c: string) => c.toUpperCase())
  key = key.replace(/[^A-Za-z0-9]/g, '')
  if (!key) key = 'route'
  if (/^\d/.test(key)) key = `r${key}`
  return key.charAt(0).toLowerCase() + key.slice(1)
}

function fallbackPropertyPath(routePath: string): string[] {
  const segments = routePath.split('/').filter(Boolean)
  if (segments.length === 0) return ['home']
  return segments.map(sanitizeKey)
}

function isRouteNode(value: RouteValue | undefined): value is RouteNode {
  return typeof value === 'object' && value !== null
}

function assignRoute(tree: RouteNode, path: string[], routePath: string) {
  let node: RouteNode = tree
  for (let i = 0; i < path.length; i++) {
    const key = path[i]!
    if (i === path.length - 1) {
      node[key] = routePath
      continue
    }
    const existing = node[key]
    if (!isRouteNode(existing)) {
      const child: RouteNode = {}
      node[key] = child
      node = child
    } else {
      node = existing
    }
  }
}

function buildRoutesFile(entries: ManifestEntry[], routesConfig: RoutesConfig): string {
  const tree: RouteNode = {}
  const paths = new Set(entries.map(e => e.routePath))
  for (const extraPath of Object.keys(routesConfig)) {
    paths.add(extraPath)
  }

  for (const routePath of Array.from(paths).toSorted()) {
    const configured = routesConfig[routePath]
    const propertyPaths =
      configured && configured.length > 0 ? configured : [fallbackPropertyPath(routePath)]
    for (const propertyPath of propertyPaths) {
      assignRoute(tree, propertyPath, routePath)
    }
  }

  const serialized = serializeTree(tree, 0)

  const contents = `// This file is auto-generated by the route manifest generator.
// Do not edit manually.
import { route } from '@/honostar/server'

export const routes = route(${serialized})

export type Routes = typeof routes
`
  return contents
}

function serializeTree(node: RouteValue, indentLevel: number): string {
  const indent = '  '.repeat(indentLevel)
  if (typeof node === 'string') {
    return `'${node}'`
  }
  const entries = Object.entries(node).toSorted(([a], [b]) => a.localeCompare(b))
  const inner = entries
    .map(([key, value]) => `${indent}  ${key}: ${serializeTree(value, indentLevel + 1)},`)
    .join('\n')
  return `{\n${inner}\n${indent}}`
}

export async function generateRouteManifest(options: GeneratorOptions): Promise<void> {
  const { pagesDir, manifestPath, routesPath, routesConfig = {} } = options

  // Build entries
  const entries = await buildEntries(pagesDir, manifestPath)

  // Ensure output directory exists
  await mkdir(dirname(manifestPath), { recursive: true })

  // Write manifest file
  const manifestContent = generateManifestFile(entries)
  await writeFile(manifestPath, manifestContent, 'utf-8')

  // Write routes file
  const routesContent = buildRoutesFile(entries, routesConfig)
  await writeFile(routesPath, routesContent, 'utf-8')
}
