import fs from 'node:fs/promises'
import path from 'node:path'
import { Glob } from 'bun'
import { filePathToRoutePath } from '../src/core/path-utils'

const routesDir = path.join(process.cwd(), 'src/routes')
const outputFile = path.join(process.cwd(), 'src/lib/api-routes.generated.ts')
const glob = new Glob('**/*.{ts,tsx}')

let pageRoutes = ''
let actionRoutes = ''

const pathToKey = (p: string) => {
  return p.replace(/^\//, '').replace(/[/:-]/g, '_').replace(/\[|\]/g, '') || 'index'
}

for (const file of glob.scanSync({ cwd: routesDir })) {
  const fullPath = path.join(routesDir, file)
  const routePath = filePathToRoutePath(path.join('src/routes', file))
  const key = pathToKey(routePath)

  const content = await fs.readFile(fullPath, 'utf-8')

  const hasDefaultExport = /\bexport\s+default\b/.test(content)
  const hasActionExport = /\bexport\s+const\s+(GET|POST|PUT|PATCH|DELETE)\b/.test(content)

  const params = [...routePath.matchAll(/:(\w+)/g)].map(m => m[1])
  let routeEntry = ''

  if (params.length > 0) {
    const paramsType = `{ ${params.map(p => `${p}: string | number`).join(', ')} }`
    const templateLiteral = routePath.replace(/:(\w+)/g, (_, param) => `\${params.${param}}`)
    routeEntry = `  ${key}: (params: ${paramsType}) => \`${templateLiteral}\`,\n`
  } else {
    routeEntry = `  ${key}: '${routePath}',\n`
  }

  if (hasDefaultExport) {
    pageRoutes += routeEntry
  }
  if (hasActionExport) {
    actionRoutes += routeEntry
  }
}

const fileContent = `// This file is auto-generated by scripts/generate-routes.ts
// Do not edit this file directly.

export const R = {
  pages: {
${pageRoutes}  },
  actions: {
${actionRoutes}  },
} as const
`

await fs.writeFile(outputFile, fileContent)

console.log(`✓ API routes generated at ${outputFile}`)
