#!/usr/bin/env bun
import { mkdir } from 'node:fs/promises'
import { dirname, join, posix, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import routesConfigJson from './routes.config.json' with { type: 'json' }

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const pagesDir = resolve(repoRoot, 'src/pages')
const manifestPath = resolve(repoRoot, 'src/routes.manifest.ts')
const routesPath = resolve(repoRoot, 'src/routes.ts')

const glob = new Bun.Glob('**/*.{ts,tsx}')

type ManifestEntry = {
  routePath: string
  importPath: string
}

function filePathToRoutePath(filePath: string): string {
  let p = filePath
    .replace(/\\/g, '/')
    .replace(/^.*\/pages\//, '')
    .replace(/\.(tsx|ts|mdx|md)$/, '')

  p = p.replace(/\((.+?)\)/g, '')
  p = p.replace(/\[\.{3}.*\]/g, '*')
  p = p.replace(/\[(.+?)\]/g, ':$1')
  p = p.replace(/\/index$/, '')
  if (p === 'index') p = ''
  p = '/' + p
  return p.replace(/\/\/+/g, '/')
}

function shouldSkip(filePath: string): boolean {
  return /\/_[^/]+\.(ts|tsx)$/.test(filePath)
}

async function ensureDirForFile(path: string) {
  await mkdir(dirname(path), { recursive: true })
}

function countDynamicSegments(path: string): number {
  return path
    .split('/')
    .filter(seg => seg.startsWith(':') || seg === '*' || seg === '*?' || seg === '**').length
}

function buildEntries(): ManifestEntry[] {
  const entries: ManifestEntry[] = []

  for (const rel of glob.scanSync({ cwd: pagesDir })) {
    if (shouldSkip(rel)) continue

    const abs = join(pagesDir, rel)
    const routePath = filePathToRoutePath(abs)
    const relativeToManifest = relative(dirname(manifestPath), abs)
    const withoutExt = relativeToManifest.replace(/\.(tsx|ts)$/, '')
    const importPath = './' + posix.join(...withoutExt.split(/[/\\]+/))

    entries.push({ routePath, importPath })
  }

  return entries.sort((a, b) => {
    const aDynamic = countDynamicSegments(a.routePath)
    const bDynamic = countDynamicSegments(b.routePath)
    if (aDynamic !== bDynamic) return aDynamic - bDynamic
    // When dynamics equal, prefer longer/static paths first so `/issues/new` beats `/issues/:id`
    if (a.routePath.length !== b.routePath.length) return b.routePath.length - a.routePath.length
    return a.routePath.localeCompare(b.routePath)
  })
}

function generateManifestFile(entries: ManifestEntry[]) {
  const lines: string[] = []
  lines.push('// This file is auto-generated by scripts/generate-route-manifest.ts')
  lines.push('// Do not edit manually.')
  lines.push("import type { RouteManifestEntry } from '@/core/router/manifest-route-loader'")
  lines.push('')
  lines.push('export const routesManifest: RouteManifestEntry[] = [')
  for (const entry of entries) {
    lines.push('  {')
    lines.push(`    routePath: ${JSON.stringify(entry.routePath)},`)
    lines.push(`    load: () => import(${JSON.stringify(entry.importPath)}),`)
    lines.push('  },')
  }
  lines.push(']')
  lines.push('')
  return lines.join('\n')
}

type RoutesConfig = Record<string, string[][]>

const routesConfig: RoutesConfig = Object.fromEntries(
  Object.entries(routesConfigJson as Record<string, unknown>).map(([path, value]) => [
    path,
    normalizeConfigValue(value),
  ])
)

type RouteValue = string | RouteNode
interface RouteNode {
  [key: string]: RouteValue
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every(item => typeof item === 'string')
}

function isStringArrayArray(value: unknown): value is string[][] {
  return (
    Array.isArray(value) &&
    value.every(item => Array.isArray(item) && item.every(inner => typeof inner === 'string'))
  )
}

function normalizeConfigValue(value: unknown): string[][] {
  if (typeof value === 'string') return [[value]]
  if (isStringArray(value)) return [value]
  if (isStringArrayArray(value)) return value
  throw new Error(`Invalid routes config entry: ${JSON.stringify(value)}`)
}

function sanitizeKey(segment: string): string {
  let key = segment.replace(/^:/, '')
  key = key.replace(/\[(\.\.\.)?/, '').replace(/]/g, '')
  if (segment.startsWith('*')) key = 'wildcard'
  if (segment.startsWith('...')) key = `rest${key}`
  if (!key || key === '') key = 'index'
  key = key.replace(/[^A-Za-z0-9]+(\w)/g, (_, c: string) => c.toUpperCase())
  key = key.replace(/[^A-Za-z0-9]/g, '')
  if (!key) key = 'route'
  if (/^\d/.test(key)) key = `r${key}`
  return key.charAt(0).toLowerCase() + key.slice(1)
}

function fallbackPropertyPath(routePath: string): string[] {
  const segments = routePath.split('/').filter(Boolean)
  if (segments.length === 0) return ['home']
  return segments.map(sanitizeKey)
}

function isRouteNode(value: RouteValue | undefined): value is RouteNode {
  return typeof value === 'object' && value !== null
}

function assignRoute(tree: RouteNode, path: string[], routePath: string) {
  let node: RouteNode = tree
  for (let i = 0; i < path.length; i++) {
    const key = path[i]!
    if (i === path.length - 1) {
      node[key] = routePath
      continue
    }
    const existing = node[key]
    if (!isRouteNode(existing)) {
      const child: RouteNode = {}
      node[key] = child
      node = child
    } else {
      node = existing
    }
  }
}

function buildRoutesFile(entries: ManifestEntry[]) {
  const tree: RouteNode = {}
  const paths = new Set(entries.map(e => e.routePath))
  for (const extraPath of Object.keys(routesConfig)) {
    paths.add(extraPath)
  }

  for (const routePath of Array.from(paths).sort()) {
    const configured = routesConfig[routePath]
    const propertyPaths =
      configured && configured.length > 0 ? configured : [fallbackPropertyPath(routePath)]
    for (const propertyPath of propertyPaths) {
      assignRoute(tree, propertyPath, routePath)
    }
  }

  const serialized = serializeTree(tree, 0)

  const contents = `// This file is auto-generated by scripts/generate-route-manifest.ts
// Do not edit manually.
import { route } from '@/core/route'

export const routes = route(${serialized})

export type Routes = typeof routes
`
  return contents
}

function serializeTree(node: RouteValue, indentLevel: number): string {
  const indent = '  '.repeat(indentLevel)
  if (typeof node === 'string') {
    return `'${node}'`
  }
  const entries = Object.entries(node).toSorted(([a], [b]) => a.localeCompare(b))
  const inner = entries
    .map(([key, value]) => `${indent}  ${key}: ${serializeTree(value, indentLevel + 1)},`)
    .join('\n')
  return `{\n${inner}\n${indent}}`
}

async function main() {
  const entries = buildEntries()
  await ensureDirForFile(manifestPath)
  await Bun.write(manifestPath, generateManifestFile(entries))
  console.log(`Wrote ${entries.length} routes to ${relative(repoRoot, manifestPath)}`)

  await Bun.write(routesPath, buildRoutesFile(entries))
  console.log(`Updated routes definition at ${relative(repoRoot, routesPath)}`)
}

await main()
