import fs from 'node:fs/promises'
import path from 'node:path'
import { Glob } from 'bun'
import { filePathToRoutePath } from '@/core/path-utils'

const routesDir = path.join(process.cwd(), 'src/routes')
const outputFile = path.join(process.cwd(), 'src/lib/_routes.ts')
const glob = new Glob('**/*.{ts,tsx}')

const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const
type Method = (typeof METHODS)[number]

function isMethod(s: string | undefined): s is Method {
  return !!s && (METHODS as readonly string[]).includes(s)
}

const typeImports = new Set<string>()
const actionHelpers: string[] = []
const pageRoutes: string[] = []
const actionRoutePaths: string[] = []
const schemaDefinitions = new Map<string, string>()

const pathToKey = (p: string) => {
  return p.replace(/^\//, '').replace(/[/:-]/g, '_').replace(/\[|\]/g, '') || 'index'
}

for (const file of glob.scanSync({ cwd: routesDir })) {
  const fullPath = path.join(routesDir, file)
  const routePath = filePathToRoutePath(path.join('src/routes', file))
  const key = pathToKey(routePath)
  const content = await fs.readFile(fullPath, 'utf-8')

  const hasDefaultExport = /\bexport\s+default\b/.test(content)
  const methodMatches = [...content.matchAll(/\bexport\s+const\s+((GET|POST|PUT|PATCH|DELETE))\b/g)]
  const exportedMethods = Array.from(new Set(methodMatches.map(m => m[1]))).filter(isMethod)

  const params: string[] = [...routePath.matchAll(/:(\w+)/g)]
    .map(m => m[1])
    .filter((p): p is string => !!p)

  if (hasDefaultExport) {
    let pageEntry = `  ${key}: `
    if (params.length > 0) {
      const paramsType = `{ ${params.map(p => `${p}: string`).join(', ')} }`
      const templateLiteral = routePath.replace(/:(\w+)/g, (_, param) => `\${params.${param}}`)
      pageEntry += `(params: ${paramsType}) => \`${templateLiteral}\`,\n`
    } else {
      pageEntry += `'${routePath}',\n`
    }
    pageRoutes.push(pageEntry)
  }

  if (exportedMethods.length > 0) {
    let actionPathEntry = `  ${key}: `
    if (params.length > 0) {
      const paramsType = `{ ${params.map(p => `${p}: string`).join(', ')} }`
      const templateLiteral = routePath.replace(/:(\w+)/g, (_, param) => `\${params.${param}}`)
      actionPathEntry += `(params: ${paramsType}) => \`${templateLiteral}\`,\n`
    } else {
      actionPathEntry += `'${routePath}',\n`
    }
    actionRoutePaths.push(actionPathEntry)

    for (const method of exportedMethods) {
      const actionKey = `${key}.${method.toLowerCase()}`
      const hasBody = ['POST', 'PUT', 'PATCH'].includes(method)

      const schemaRegex = new RegExp(
        `export\\s+const\\s+(?!(?:Params?|Param|Query))(?:${method.toLowerCase()}Schema|bodySchema|formSchema|schema)\\s*=\\s*(z\\.object\\([\\s\\S]*?\\))(?:\\s*//.*?)?(?=\\s*(?:export|const\\s+(?:Params?)))`,
        's'
      )
      const schemaMatch = content.match(schemaRegex)

      let actionHelper = `  '${actionKey}': `
      const paramsArg =
        params.length > 0 ? `params: { ${params.map(p => `${p}: string`).join(', ')} }` : ''
      const pathCall = params.length > 0 ? `R.actions.${key}(params)` : JSON.stringify(routePath)

      if (hasBody && schemaMatch) {
        const schemaName = `schema_${key}_${method.toLowerCase()}`
        schemaDefinitions.set(schemaName, `const ${schemaName} = ${schemaMatch[1]}`)
        typeImports.add("import { z } from 'zod'")

        const schemaType = `z.infer<typeof ${schemaName}>`
        const finalParams = [paramsArg, `input: ${schemaType}`].filter(Boolean).join(', ')

        if (params.length > 0) {
          actionHelper += `(${finalParams}) => \`@${method.toLowerCase()}('\${${pathCall}}', \${JSON.stringify(input)})\`,\n`
        } else {
          actionHelper += `(${finalParams}) => \`@${method.toLowerCase()}(${JSON.stringify(routePath)}, \${JSON.stringify(input)})\`,\n`
        }

        if (method === 'POST') {
          const formActionKey = `${actionKey}.form`
          if (params.length > 0) {
            actionHelpers.push(
              `  '${formActionKey}': (${paramsArg}) => \`@post('\${${pathCall}}', { contentType: "form" })\`,\n`
            )
          } else {
            actionHelpers.push(
              `  '${formActionKey}': () => \`@post(${JSON.stringify(routePath)}, { contentType: "form" })\`,\n`
            )
          }
        }
      } else {
        if (params.length > 0) {
          actionHelper += `(${paramsArg}) => \`@${method.toLowerCase()}('\${${pathCall}}')\`,\n`
        } else {
          actionHelper += `() => \`@${method.toLowerCase()}(${JSON.stringify(routePath)})\`,\n`
        }
      }
      actionHelpers.push(actionHelper)
    }
  }
}

const fileContent = `// This file is auto-generated by scripts/generate-routes.ts
// Do not edit this file directly.

${Array.from(typeImports).join('\n')}

${Array.from(schemaDefinitions.values()).join('\n\n')}

export const R = {
  pages: {
${pageRoutes.join('')}  },
  actions: {
${actionRoutePaths.join('')}  },
} as const

// Typed action helpers - use these in JSX
export const actions = {
${actionHelpers.join('')}} as const
`

await fs.writeFile(outputFile, fileContent)

console.log(`✓ Schema-aware API routes generated at ${outputFile}`)
