// This file is auto-generated by the route manifest generator.
// Do not edit manually.
import { route } from "@honostar/core/server"

export const routes = route({
  home: "/",
  increment: "/increment",
})

export type Routes = typeof routes
