// This file is auto-generated by the route manifest generator.
// Do not edit manually.
import type { RouteManifestEntry } from '@honostar/core/server'

export const routesManifest: RouteManifestEntry[] = [
  {
    routePath: '/increment',
    load: () => import('./pages/increment'),
  },
  {
    routePath: '/',
    load: () => import('./pages/index'),
  },
]
