// This file is auto-generated by the route manifest generator.
// Do not edit manually.
import { route } from '@/core/route'

export const routes = route({
  auth: {
    action: '/auth/:action',
    login: '/login',
    logout: '/logout',
    profile: '/profile',
  },
  home: '/',
  issues: {
    comments: '/issues/:id/comments',
    create: '/issues',
    list: '/issues',
    new: '/issues/new',
    show: '/issues/:id',
  },
  labels: '/labels',
  signup: '/signup',
  sse: '/_/events',
})

export type Routes = typeof routes
