// This file is auto-generated by scripts/generate-route-manifest.ts
// Do not edit manually.
import type { RouteManifestEntry } from '@/core/router/manifest-route-loader'

export const routesManifest: RouteManifestEntry[] = [
  {
    routePath: "/issues/new",
    load: () => import("./pages/issues/new"),
  },
  {
    routePath: "/profile",
    load: () => import("./pages/profile"),
  },
  {
    routePath: "/issues",
    load: () => import("./pages/issues"),
  },
  {
    routePath: "/labels",
    load: () => import("./pages/labels"),
  },
  {
    routePath: "/logout",
    load: () => import("./pages/logout"),
  },
  {
    routePath: "/login",
    load: () => import("./pages/login"),
  },
  {
    routePath: "/",
    load: () => import("./pages/index"),
  },
  {
    routePath: "/issues/:id/comments",
    load: () => import("./pages/issues/[id]/comments"),
  },
  {
    routePath: "/auth/:action",
    load: () => import("./pages/auth/[action]"),
  },
  {
    routePath: "/issues/:id",
    load: () => import("./pages/issues/[id]"),
  },
]
