// This file is auto-generated by the route manifest generator.
// Do not edit manually.
import type { RouteManifestEntry } from '@/honostar/server'

export const routesManifest: RouteManifestEntry[] = [
  {
    routePath: '/inspector-demo',
    load: () => import('./pages/inspector-demo'),
  },
  {
    routePath: '/issues/new',
    load: () => import('./pages/issues/new'),
  },
  {
    routePath: '/profile',
    load: () => import('./pages/profile'),
  },
  {
    routePath: '/issues',
    load: () => import('./pages/issues'),
  },
  {
    routePath: '/labels',
    load: () => import('./pages/labels'),
  },
  {
    routePath: '/logout',
    load: () => import('./pages/logout'),
  },
  {
    routePath: '/search',
    load: () => import('./pages/search'),
  },
  {
    routePath: '/signup',
    load: () => import('./pages/signup'),
  },
  {
    routePath: '/login',
    load: () => import('./pages/login'),
  },
  {
    routePath: '/',
    load: () => import('./pages/index'),
  },
  {
    routePath: '/issues/:id/comments',
    load: () => import('./pages/issues/[id]/comments'),
  },
  {
    routePath: '/auth/:action',
    load: () => import('./pages/auth/[action]'),
  },
  {
    routePath: '/issues/:id',
    load: () => import('./pages/issues/[id]'),
  },
]
